### ISSUE TITLE
Improve build log UI

### ISSUE THREAD

**Issue by estebanreyl** [AzureCR/vscode-docker#48]
- Remove Registry field
- Padding for output images, semi bold, left align
- Truncate digest, copy item next to it
- Left align titles with the column
- Left align all columns
? to ‘’
Status- unify color with vscode and no bold.
Change top bar to foreground color titles
- Change Error/Failed, etc foreground on selection.

**Comment by northtyphoon** [comment]
Fixed in PR #72
